name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install Google Chrome
      - name: Install Google Chrome
        run:
          brew install --cask google-chrome

      # Install ChromeDriver
      - name: Install ChromeDriver
        run:
            # Download ChromeDriver
            wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac64.zip
            # Unzip ChromeDriver
            unzip chromedriver_mac64.zip
            # Move ChromeDriver to the correct location
            sudo mv chromedriver /usr/local/bin/chromedriver
            # Give execute permissions
            sudo chmod +x /usr/local/bin/chromedriver

      # Set up virtual display (XQuartz for macOS)
      - name: Install XQuartz
        run: brew install --cask xquartz

      - name: Start XQuartz
        run: |
          open -a XQuartz
          export DISPLAY=:0

      # Run Selenium tests
      - name: Run Selenium tests
        run: mvn clean verify -Dtestng.dtd.http=true
          # Your command to run the Selenium tests (e.g., mvn test, gradle test)